export interface Product {
  id: string;
  name: string;
  price: string;
  originalPrice?: string;
  delivery: string;
  image: string;
  category: string;
  rating: number;
  reviews: number;
  description: string;
  featured?: boolean;
}

export const categories = [
  { id: 'all', name: 'All Products', icon: '📱' },
  { id: 'smartphones', name: 'Smartphones', icon: '📱' },
  { id: 'laptops', name: 'Laptops', icon: '💻' },
  { id: 'audio', name: 'Audio', icon: '🎧' },
  { id: 'wearables', name: 'Wearables', icon: '⌚' },
  { id: 'tablets', name: 'Tablets', icon: '📱' },
  { id: 'smart-home', name: 'Smart Home', icon: '🏠' },
  { id: 'cameras', name: 'Cameras', icon: '📷' },
  { id: 'tv', name: 'TV & Display', icon: '📺' },
];

export const products: Product[] = [
  {
    id: '1',
    name: "iPhone 14 Pro",
    price: "$999",
    originalPrice: "$1099",
    delivery: "Free Shipping",
    image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&h=400&fit=crop",
    category: "smartphones",
    rating: 4.8,
    reviews: 2847,
    description: "The most advanced iPhone with Pro camera system and A16 Bionic chip.",
    featured: true,
  },
  {
    id: '2',
    name: "Samsung Galaxy S23",
    price: "$799",
    delivery: "Standard Shipping",
    image: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400&h=400&fit=crop",
    category: "smartphones",
    rating: 4.6,
    reviews: 1923,
    description: "Flagship Android phone with exceptional camera and performance.",
  },
  {
    id: '3',
    name: "Google Pixel 7 Pro",
    price: "$599",
    delivery: "Free Shipping",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop",
    category: "smartphones",
    rating: 4.5,
    reviews: 1456,
    description: "Pure Android experience with incredible computational photography.",
  },
  {
    id: '4',
    name: "Sony WH-1000XM5",
    price: "$349",
    originalPrice: "$399",
    delivery: "Express Shipping",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    category: "audio",
    rating: 4.9,
    reviews: 3421,
    description: "Industry-leading noise canceling wireless headphones.",
    featured: true,
  },
  {
    id: '5',
    name: "MacBook Pro 14\"",
    price: "$1,999",
    delivery: "Free Shipping",
    image: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400&h=400&fit=crop",
    category: "laptops",
    rating: 4.8,
    reviews: 2156,
    description: "Supercharged by M2 Pro chip for demanding workflows.",
    featured: true,
  },
  {
    id: '6',
    name: "Dell XPS 13",
    price: "$1,199",
    delivery: "Free Shipping",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop",
    category: "laptops",
    rating: 4.4,
    reviews: 1789,
    description: "Ultra-portable laptop with stunning InfinityEdge display.",
  },
  {
    id: '7',
    name: "iPad Pro 12.9\"",
    price: "$1,099",
    delivery: "Standard Shipping",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop",
    category: "tablets",
    rating: 4.7,
    reviews: 2934,
    description: "The ultimate iPad experience with M2 chip and Liquid Retina XDR display.",
  },
  {
    id: '8',
    name: "Kindle Paperwhite",
    price: "$139",
    delivery: "Free Shipping",
    image: "https://images.unsplash.com/photo-1481277542470-605612bd2d61?w=400&h=400&fit=crop",
    category: "tablets",
    rating: 4.3,
    reviews: 8765,
    description: "Waterproof e-reader with adjustable warm light and weeks of battery life.",
  },
  {
    id: '9',
    name: "Apple Watch Series 9",
    price: "$399",
    delivery: "Free Shipping",
    image: "https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=400&h=400&fit=crop",
    category: "wearables",
    rating: 4.6,
    reviews: 4521,
    description: "Advanced health features and the brightest Apple Watch display ever.",
  },
  {
    id: '10',
    name: "Fitbit Charge 6",
    price: "$179",
    originalPrice: "$199",
    delivery: "Standard Shipping",
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400&h=400&fit=crop",
    category: "wearables",
    rating: 4.2,
    reviews: 2876,
    description: "Advanced fitness tracker with built-in GPS and heart rate monitoring.",
  },
  {
    id: '11',
    name: "Google Nest Hub Max",
    price: "$229",
    delivery: "Free Shipping",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop",
    category: "smart-home",
    rating: 4.4,
    reviews: 1654,
    description: "Smart display with Google Assistant and built-in Nest Cam.",
  },
  {
    id: '12',
    name: "Bose QuietComfort 45",
    price: "$329",
    delivery: "Express Shipping",
    image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400&h=400&fit=crop",
    category: "audio",
    rating: 4.5,
    reviews: 2341,
    description: "Wireless noise cancelling headphones with exceptional comfort.",
  },
  {
    id: '13',
    name: "LG OLED C3 55\"",
    price: "$1,499",
    originalPrice: "$1,799",
    delivery: "Free Shipping",
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=400&fit=crop",
    category: "tv",
    rating: 4.8,
    reviews: 1876,
    description: "Self-lit OLED pixels deliver perfect black and intense color.",
    featured: true,
  },
  {
    id: '14',
    name: "Microsoft Surface Pro 9",
    price: "$899",
    delivery: "Standard Shipping",
    image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400&h=400&fit=crop",
    category: "tablets",
    rating: 4.3,
    reviews: 1432,
    description: "2-in-1 laptop and tablet with all-day battery life.",
  },
  {
    id: '15',
    name: "GoPro HERO12 Black",
    price: "$399",
    delivery: "Express Shipping",
    image: "https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?w=400&h=400&fit=crop",
    category: "cameras",
    rating: 4.6,
    reviews: 3245,
    description: "Most versatile action camera with 5.3K video and HyperSmooth 6.0.",
  },
  {
    id: '16',
    name: "JBL Charge 5",
    price: "$179",
    delivery: "Standard Shipping",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop",
    category: "audio",
    rating: 4.4,
    reviews: 2987,
    description: "Portable Bluetooth speaker with powerful sound and powerbank feature.",
  },
];
